export enum OtpType {
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
  PASSWORD_RESET = "PASSWORD_RESET",
  PHONE_VERIFICATION = "PHONE_VERIFICATION",
  TWO_FACTOR_AUTH = "TWO_FACTOR_AUTH",
  NULL=""
}
