// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCkA2_VDVb9GC2cFaLMET0mM8UzRg9kYcs",
    authDomain: "track-9cb11.firebaseapp.com",
    projectId: "track-9cb11",
    storageBucket: "track-9cb11.firebasestorage.app",
    messagingSenderId: "917443098038",
    appId: "1:917443098038:web:69dab3fed1c90294923d17",
    measurementId: "G-C0STWRD1HQ",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPB9rr6OtDEapdFxJFRWm6ZFOihV4R7Qc',
    appId: '1:917443098038:android:d4ae7c3515dfcca8923d17',
    messagingSenderId: '917443098038',
    projectId: 'track-9cb11',
    storageBucket: 'track-9cb11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPB9rr6OtDEapdFxJFRWm6ZFOihV4R7Qc',
    appId: '1:917443098038:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '917443098038',
    projectId: 'track-9cb11',
    storageBucket: 'track-9cb11.firebasestorage.app',
    iosBundleId: 'com.track.seven.omega.app',
  );
}
